const TOPICS = [
  // === GENERAL (65 topics) ===
  { id: 1, text: "What is the best advice you have ever received?", category: "general", difficulty: "easy" },
  { id: 2, text: "What is your favorite way to spend a weekend?", category: "general", difficulty: "easy" },
  { id: 3, text: "What is a skill you would like to learn and why?", category: "general", difficulty: "easy" },
  { id: 4, text: "What is the most interesting place you have ever visited?", category: "general", difficulty: "easy" },
  { id: 5, text: "What book has had the biggest impact on your life?", category: "general", difficulty: "easy" },
  { id: 6, text: "What does a perfect day look like for you?", category: "general", difficulty: "easy" },
  { id: 7, text: "What is one thing most people don't know about you?", category: "general", difficulty: "easy" },
  { id: 8, text: "What is the most valuable lesson you learned in school?", category: "general", difficulty: "easy" },
  { id: 9, text: "If you could live in any city in the world, where would it be?", category: "general", difficulty: "easy" },
  { id: 10, text: "What is the best movie you have seen this year?", category: "general", difficulty: "easy" },
  { id: 11, text: "What hobby have you always wanted to pick up?", category: "general", difficulty: "easy" },
  { id: 12, text: "What is one thing you cannot live without?", category: "general", difficulty: "easy" },
  { id: 13, text: "What is the most memorable meal you have ever had?", category: "general", difficulty: "easy" },
  { id: 14, text: "What is a cause you feel strongly about?", category: "general", difficulty: "medium" },
  { id: 15, text: "How do you define success?", category: "general", difficulty: "medium" },
  { id: 16, text: "What role does music play in your life?", category: "general", difficulty: "medium" },
  { id: 17, text: "What is the most challenging thing you have ever done?", category: "general", difficulty: "medium" },
  { id: 18, text: "How has technology changed the way you communicate?", category: "general", difficulty: "medium" },
  { id: 19, text: "What tradition do you cherish the most?", category: "general", difficulty: "medium" },
  { id: 20, text: "What is your favorite season and why?", category: "general", difficulty: "easy" },
  { id: 21, text: "What does home mean to you?", category: "general", difficulty: "medium" },
  { id: 22, text: "Describe a moment that changed your perspective on life.", category: "general", difficulty: "medium" },
  { id: 23, text: "What is the best gift you have ever given or received?", category: "general", difficulty: "easy" },
  { id: 24, text: "How do you handle stress in your daily life?", category: "general", difficulty: "medium" },
  { id: 25, text: "What is one small thing that makes your day better?", category: "general", difficulty: "easy" },
  { id: 26, text: "What is the most beautiful thing you have ever seen?", category: "general", difficulty: "easy" },
  { id: 27, text: "How important is it to have a routine?", category: "general", difficulty: "medium" },
  { id: 28, text: "What is a food you thought you would hate but ended up loving?", category: "general", difficulty: "easy" },
  { id: 29, text: "What is the best compliment you have ever received?", category: "general", difficulty: "easy" },
  { id: 30, text: "What is a simple pleasure that you enjoy?", category: "general", difficulty: "easy" },
  { id: 31, text: "How do you recharge after a long week?", category: "general", difficulty: "easy" },
  { id: 32, text: "What is the most useful thing you own?", category: "general", difficulty: "easy" },
  { id: 33, text: "What is a life lesson you wish you had learned sooner?", category: "general", difficulty: "medium" },
  { id: 34, text: "How do you stay motivated when things get tough?", category: "general", difficulty: "medium" },
  { id: 35, text: "What is something you are grateful for today?", category: "general", difficulty: "easy" },
  { id: 36, text: "What is the best way to make new friends as an adult?", category: "general", difficulty: "medium" },
  { id: 37, text: "What is a documentary that blew your mind?", category: "general", difficulty: "easy" },
  { id: 38, text: "How do you decide what is worth your time?", category: "general", difficulty: "medium" },
  { id: 39, text: "What is the best spontaneous decision you have ever made?", category: "general", difficulty: "medium" },
  { id: 40, text: "What does balance in life look like to you?", category: "general", difficulty: "medium" },
  { id: 41, text: "What is your favorite way to learn something new?", category: "general", difficulty: "easy" },
  { id: 42, text: "What is the best conversation you have ever had?", category: "general", difficulty: "medium" },
  { id: 43, text: "What is one thing you would tell your younger self?", category: "general", difficulty: "medium" },
  { id: 44, text: "What is a trend you hope never goes away?", category: "general", difficulty: "easy" },
  { id: 45, text: "How do you celebrate your achievements?", category: "general", difficulty: "easy" },
  { id: 46, text: "What is the most interesting fact you know?", category: "general", difficulty: "easy" },
  { id: 47, text: "What role does nature play in your well-being?", category: "general", difficulty: "medium" },
  { id: 48, text: "What is something you have changed your mind about?", category: "general", difficulty: "medium" },
  { id: 49, text: "How important is it to step outside your comfort zone?", category: "general", difficulty: "medium" },
  { id: 50, text: "What is the best piece of wisdom from your grandparents?", category: "general", difficulty: "medium" },
  { id: 51, text: "What would you do with an unexpected day off?", category: "general", difficulty: "easy" },
  { id: 52, text: "What is a cultural experience that left an impression on you?", category: "general", difficulty: "medium" },
  { id: 53, text: "What is the best thing about the era we live in?", category: "general", difficulty: "medium" },
  { id: 54, text: "How do you define kindness?", category: "general", difficulty: "medium" },
  { id: 55, text: "What is the most overrated thing in modern life?", category: "general", difficulty: "medium" },
  { id: 56, text: "What is the most underrated thing in modern life?", category: "general", difficulty: "medium" },
  { id: 57, text: "What is the best local restaurant and what makes it special?", category: "general", difficulty: "easy" },
  { id: 58, text: "How has a pet changed your life?", category: "general", difficulty: "easy" },
  { id: 59, text: "What is a skill that everyone should learn?", category: "general", difficulty: "medium" },
  { id: 60, text: "What is your favorite thing about where you live?", category: "general", difficulty: "easy" },
  { id: 61, text: "What is the most important quality in a friend?", category: "general", difficulty: "medium" },
  { id: 62, text: "How do you stay curious as you get older?", category: "general", difficulty: "medium" },
  { id: 63, text: "What is the best road trip you have ever taken?", category: "general", difficulty: "easy" },
  { id: 64, text: "What does it mean to live a good life?", category: "general", difficulty: "hard" },
  { id: 65, text: "What is something that always makes you smile?", category: "general", difficulty: "easy" },

  // === PHILOSOPHICAL (65 topics) ===
  { id: 66, text: "Is it ever acceptable to lie?", category: "philosophical", difficulty: "hard" },
  { id: 67, text: "What is the meaning of life?", category: "philosophical", difficulty: "hard" },
  { id: 68, text: "Is free will an illusion?", category: "philosophical", difficulty: "hard" },
  { id: 69, text: "Can money buy happiness?", category: "philosophical", difficulty: "medium" },
  { id: 70, text: "Is it better to be feared or respected?", category: "philosophical", difficulty: "medium" },
  { id: 71, text: "Does absolute power corrupt absolutely?", category: "philosophical", difficulty: "hard" },
  { id: 72, text: "What makes something beautiful?", category: "philosophical", difficulty: "hard" },
  { id: 73, text: "Is there such a thing as a selfless act?", category: "philosophical", difficulty: "hard" },
  { id: 74, text: "Are humans inherently good or evil?", category: "philosophical", difficulty: "hard" },
  { id: 75, text: "What is the relationship between knowledge and wisdom?", category: "philosophical", difficulty: "hard" },
  { id: 76, text: "Is ignorance truly bliss?", category: "philosophical", difficulty: "medium" },
  { id: 77, text: "Should we judge people by their intentions or their actions?", category: "philosophical", difficulty: "hard" },
  { id: 78, text: "What does justice really mean?", category: "philosophical", difficulty: "hard" },
  { id: 79, text: "Is it possible to be truly objective?", category: "philosophical", difficulty: "hard" },
  { id: 80, text: "Does suffering have a purpose?", category: "philosophical", difficulty: "hard" },
  { id: 81, text: "What is the value of art in society?", category: "philosophical", difficulty: "medium" },
  { id: 82, text: "Is privacy a right or a privilege?", category: "philosophical", difficulty: "medium" },
  { id: 83, text: "Can war ever be justified?", category: "philosophical", difficulty: "hard" },
  { id: 84, text: "What is more important: freedom or security?", category: "philosophical", difficulty: "hard" },
  { id: 85, text: "Does destiny exist or do we create our own path?", category: "philosophical", difficulty: "medium" },
  { id: 86, text: "What is the difference between living and existing?", category: "philosophical", difficulty: "medium" },
  { id: 87, text: "Is it our duty to help others?", category: "philosophical", difficulty: "medium" },
  { id: 88, text: "What does it mean to be truly free?", category: "philosophical", difficulty: "hard" },
  { id: 89, text: "Is the concept of normal harmful?", category: "philosophical", difficulty: "medium" },
  { id: 90, text: "Can you separate the art from the artist?", category: "philosophical", difficulty: "hard" },
  { id: 91, text: "Is competition healthy or destructive?", category: "philosophical", difficulty: "medium" },
  { id: 92, text: "What makes a person brave?", category: "philosophical", difficulty: "medium" },
  { id: 93, text: "Is forgiveness always the right choice?", category: "philosophical", difficulty: "medium" },
  { id: 94, text: "Should we prioritize the needs of the many over the few?", category: "philosophical", difficulty: "hard" },
  { id: 95, text: "What is the role of failure in personal growth?", category: "philosophical", difficulty: "medium" },
  { id: 96, text: "Is true equality achievable?", category: "philosophical", difficulty: "hard" },
  { id: 97, text: "What makes something morally right?", category: "philosophical", difficulty: "hard" },
  { id: 98, text: "Is it better to have loved and lost than never to have loved at all?", category: "philosophical", difficulty: "medium" },
  { id: 99, text: "What is the nature of consciousness?", category: "philosophical", difficulty: "hard" },
  { id: 100, text: "Should we fear death?", category: "philosophical", difficulty: "hard" },
  { id: 101, text: "Is there an objective truth or is everything relative?", category: "philosophical", difficulty: "hard" },
  { id: 102, text: "What defines a person's identity?", category: "philosophical", difficulty: "medium" },
  { id: 103, text: "Can technology solve all of humanity's problems?", category: "philosophical", difficulty: "medium" },
  { id: 104, text: "Is tradition a help or a hindrance to progress?", category: "philosophical", difficulty: "medium" },
  { id: 105, text: "What is the value of silence in a noisy world?", category: "philosophical", difficulty: "medium" },
  { id: 106, text: "Is it better to be a big fish in a small pond or a small fish in a big pond?", category: "philosophical", difficulty: "medium" },
  { id: 107, text: "Can you truly know another person?", category: "philosophical", difficulty: "hard" },
  { id: 108, text: "What obligations do we have to future generations?", category: "philosophical", difficulty: "hard" },
  { id: 109, text: "Is perfection a worthy goal or an impossible standard?", category: "philosophical", difficulty: "medium" },
  { id: 110, text: "What is the relationship between power and responsibility?", category: "philosophical", difficulty: "medium" },
  { id: 111, text: "Should happiness be the ultimate goal of life?", category: "philosophical", difficulty: "hard" },
  { id: 112, text: "Is nostalgia a positive or negative emotion?", category: "philosophical", difficulty: "medium" },
  { id: 113, text: "Does language shape the way we think?", category: "philosophical", difficulty: "hard" },
  { id: 114, text: "What makes a leader legitimate?", category: "philosophical", difficulty: "hard" },
  { id: 115, text: "Is it possible to change who you fundamentally are?", category: "philosophical", difficulty: "medium" },
  { id: 116, text: "What is the difference between confidence and arrogance?", category: "philosophical", difficulty: "medium" },
  { id: 117, text: "Can rules exist without exceptions?", category: "philosophical", difficulty: "medium" },
  { id: 118, text: "Is the pursuit of knowledge always worthwhile?", category: "philosophical", difficulty: "medium" },
  { id: 119, text: "What does it mean to be authentic?", category: "philosophical", difficulty: "medium" },
  { id: 120, text: "Are we defined by our choices or our circumstances?", category: "philosophical", difficulty: "hard" },
  { id: 121, text: "Is empathy a strength or a vulnerability?", category: "philosophical", difficulty: "medium" },
  { id: 122, text: "What makes something truly original?", category: "philosophical", difficulty: "hard" },
  { id: 123, text: "Is moderation always the best approach?", category: "philosophical", difficulty: "medium" },
  { id: 124, text: "What is the price of progress?", category: "philosophical", difficulty: "hard" },
  { id: 125, text: "Can a society function without trust?", category: "philosophical", difficulty: "hard" },
  { id: 126, text: "Is loyalty a virtue or a trap?", category: "philosophical", difficulty: "medium" },
  { id: 127, text: "What is the relationship between happiness and meaning?", category: "philosophical", difficulty: "hard" },
  { id: 128, text: "Should we strive for contentment or ambition?", category: "philosophical", difficulty: "medium" },
  { id: 129, text: "Is simplicity undervalued in modern life?", category: "philosophical", difficulty: "medium" },
  { id: 130, text: "What does it mean to truly listen to someone?", category: "philosophical", difficulty: "medium" },

  // === FUNNY (65 topics) ===
  { id: 131, text: "What is the most embarrassing thing that has happened to you in public?", category: "funny", difficulty: "easy" },
  { id: 132, text: "If animals could talk, which species would be the rudest?", category: "funny", difficulty: "easy" },
  { id: 133, text: "What is the worst fashion trend you ever participated in?", category: "funny", difficulty: "easy" },
  { id: 134, text: "If you had to survive on one fast food restaurant for a year, which would it be?", category: "funny", difficulty: "easy" },
  { id: 135, text: "What is the funniest misunderstanding you have ever been part of?", category: "funny", difficulty: "easy" },
  { id: 136, text: "If you could have any fictional character as a roommate, who would you choose?", category: "funny", difficulty: "easy" },
  { id: 137, text: "What is the strangest thing you have ever eaten?", category: "funny", difficulty: "easy" },
  { id: 138, text: "If you could ban one minor annoyance from existence, what would it be?", category: "funny", difficulty: "easy" },
  { id: 139, text: "What would your autobiography be titled?", category: "funny", difficulty: "medium" },
  { id: 140, text: "If your pet could suddenly speak, what would it say about you?", category: "funny", difficulty: "easy" },
  { id: 141, text: "What is the most useless talent you possess?", category: "funny", difficulty: "easy" },
  { id: 142, text: "If you were a superhero, what would your lame superpower be?", category: "funny", difficulty: "easy" },
  { id: 143, text: "What is the most ridiculous thing you believed as a child?", category: "funny", difficulty: "easy" },
  { id: 144, text: "If you had to teach a class on something you know nothing about, what would you teach?", category: "funny", difficulty: "medium" },
  { id: 145, text: "What is the worst gift you have ever received and how did you react?", category: "funny", difficulty: "easy" },
  { id: 146, text: "If you could only communicate in movie quotes for a day, how would it go?", category: "funny", difficulty: "medium" },
  { id: 147, text: "What is the most absurd rule you had to follow growing up?", category: "funny", difficulty: "easy" },
  { id: 148, text: "If aliens visited Earth, what would confuse them the most about humans?", category: "funny", difficulty: "medium" },
  { id: 149, text: "What would be the worst thing to hear as you are going under anesthesia?", category: "funny", difficulty: "medium" },
  { id: 150, text: "If you could add a totally unnecessary feature to everyday objects, what would it be?", category: "funny", difficulty: "medium" },
  { id: 151, text: "What is the most awkward elevator conversation you have had?", category: "funny", difficulty: "easy" },
  { id: 152, text: "If your life had a theme song, what would it be?", category: "funny", difficulty: "easy" },
  { id: 153, text: "What is the worst haircut you have ever had?", category: "funny", difficulty: "easy" },
  { id: 154, text: "If you had to pick a new name for yourself, what would you choose and why?", category: "funny", difficulty: "easy" },
  { id: 155, text: "What is the most questionable life hack you have ever tried?", category: "funny", difficulty: "easy" },
  { id: 156, text: "If you were a villain, what would your evil plan be?", category: "funny", difficulty: "medium" },
  { id: 157, text: "What is the funniest autocorrect fail you have experienced?", category: "funny", difficulty: "easy" },
  { id: 158, text: "If you could make one law that everyone had to follow, what ridiculous law would you create?", category: "funny", difficulty: "medium" },
  { id: 159, text: "What is the weirdest thing on your bucket list?", category: "funny", difficulty: "easy" },
  { id: 160, text: "If you had to eat the same meal every day for a month, what would it be?", category: "funny", difficulty: "easy" },
  { id: 161, text: "What is the most creative excuse you have ever used to get out of something?", category: "funny", difficulty: "easy" },
  { id: 162, text: "If you were a kitchen appliance, which one would you be?", category: "funny", difficulty: "medium" },
  { id: 163, text: "What is the most overrated activity that everyone seems to love?", category: "funny", difficulty: "medium" },
  { id: 164, text: "If you could live inside any TV show, which one would you avoid at all costs?", category: "funny", difficulty: "medium" },
  { id: 165, text: "What is the worst advice someone has confidently given you?", category: "funny", difficulty: "easy" },
  { id: 166, text: "If you had to describe your work week as a movie genre, what would it be?", category: "funny", difficulty: "medium" },
  { id: 167, text: "What is the most bizarre dream you can remember?", category: "funny", difficulty: "easy" },
  { id: 168, text: "If you could swap lives with any cartoon character for a week, who would it be?", category: "funny", difficulty: "easy" },
  { id: 169, text: "What is the most unnecessary purchase you have ever made?", category: "funny", difficulty: "easy" },
  { id: 170, text: "If you had to give a TED talk right now with no preparation, what would it be about?", category: "funny", difficulty: "medium" },
  { id: 171, text: "What is the worst DIY project you have attempted?", category: "funny", difficulty: "easy" },
  { id: 172, text: "If you could uninvent one thing, what would it be?", category: "funny", difficulty: "medium" },
  { id: 173, text: "What is the strangest compliment you have ever received?", category: "funny", difficulty: "easy" },
  { id: 174, text: "If you had to survive a zombie apocalypse with only items in your kitchen, how would you do it?", category: "funny", difficulty: "medium" },
  { id: 175, text: "What is the most irrational fear you have?", category: "funny", difficulty: "easy" },
  { id: 176, text: "If you could make any fictional food real, what would you choose?", category: "funny", difficulty: "easy" },
  { id: 177, text: "What would your wrestler name and entrance song be?", category: "funny", difficulty: "medium" },
  { id: 178, text: "What is the most dramatic way you have ever reacted to a minor inconvenience?", category: "funny", difficulty: "easy" },
  { id: 179, text: "If you had to wear one outfit for the rest of your life, what would it be?", category: "funny", difficulty: "easy" },
  { id: 180, text: "What is the funniest thing a child has ever said to you?", category: "funny", difficulty: "easy" },
  { id: 181, text: "If you could have a conversation with your refrigerator, what would it tell you?", category: "funny", difficulty: "medium" },
  { id: 182, text: "What is the most absurd thing you have argued about passionately?", category: "funny", difficulty: "easy" },
  { id: 183, text: "If you were a warning label, what would you say?", category: "funny", difficulty: "medium" },
  { id: 184, text: "What is the most unusual place you have fallen asleep?", category: "funny", difficulty: "easy" },
  { id: 185, text: "If you had to join the circus, what would your act be?", category: "funny", difficulty: "medium" },
  { id: 186, text: "What food combination do you enjoy that others find disgusting?", category: "funny", difficulty: "easy" },
  { id: 187, text: "If your GPS had a personality, whose voice would it have?", category: "funny", difficulty: "medium" },
  { id: 188, text: "What is the most ridiculous thing you have done to impress someone?", category: "funny", difficulty: "easy" },
  { id: 189, text: "If you could challenge anyone to a duel, but the weapon is something silly, what would the weapon be?", category: "funny", difficulty: "medium" },
  { id: 190, text: "What is the most embarrassing song on your playlist?", category: "funny", difficulty: "easy" },
  { id: 191, text: "If your morning routine were a sport, how would it be commentated?", category: "funny", difficulty: "medium" },
  { id: 192, text: "What is the worst date you have ever been on?", category: "funny", difficulty: "medium" },
  { id: 193, text: "If you could rename any common object, what would you rename and to what?", category: "funny", difficulty: "medium" },
  { id: 194, text: "What is the silliest reason you have cried?", category: "funny", difficulty: "easy" },
  { id: 195, text: "If you opened a restaurant that served only one item, what would it be?", category: "funny", difficulty: "easy" },

  // === HYPOTHETICAL (65 topics) ===
  { id: 196, text: "If you could have dinner with any historical figure, who would it be and why?", category: "hypothetical", difficulty: "medium" },
  { id: 197, text: "If you woke up tomorrow as the president, what is the first thing you would do?", category: "hypothetical", difficulty: "medium" },
  { id: 198, text: "If you could travel to any time period, where would you go?", category: "hypothetical", difficulty: "easy" },
  { id: 199, text: "If you could have any superpower, what would you choose and how would you use it?", category: "hypothetical", difficulty: "easy" },
  { id: 200, text: "If you could master any musical instrument overnight, which would you pick?", category: "hypothetical", difficulty: "easy" },
  { id: 201, text: "If you could relive one day of your life, which would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 202, text: "If money were no object, what would you do with your life?", category: "hypothetical", difficulty: "easy" },
  { id: 203, text: "If you could switch careers with no consequences, what would you do?", category: "hypothetical", difficulty: "easy" },
  { id: 204, text: "If you could solve one world problem, which would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 205, text: "If you could be fluent in any language instantly, which would you choose?", category: "hypothetical", difficulty: "easy" },
  { id: 206, text: "If you had to live in a different country for a year, where would you go?", category: "hypothetical", difficulty: "easy" },
  { id: 207, text: "If you could have any animal as a safe domesticated pet, what would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 208, text: "If you found a suitcase full of cash, what would you do?", category: "hypothetical", difficulty: "medium" },
  { id: 209, text: "If you could witness any event in history firsthand, which would you choose?", category: "hypothetical", difficulty: "medium" },
  { id: 210, text: "If you had one extra hour every day, how would you spend it?", category: "hypothetical", difficulty: "easy" },
  { id: 211, text: "If you could bring one fictional technology into the real world, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 212, text: "If you could read minds for a day, would you want to?", category: "hypothetical", difficulty: "medium" },
  { id: 213, text: "If you had to choose between never using the internet again or never traveling again, which would you pick?", category: "hypothetical", difficulty: "medium" },
  { id: 214, text: "If you could guarantee your children one quality, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 215, text: "If you could erase one invention from history, which would it be?", category: "hypothetical", difficulty: "hard" },
  { id: 216, text: "If you woke up with the ability to fly, what would you do first?", category: "hypothetical", difficulty: "easy" },
  { id: 217, text: "If you could send a message to the entire world, what would you say?", category: "hypothetical", difficulty: "medium" },
  { id: 218, text: "If you could be invisible for a day, what would you do?", category: "hypothetical", difficulty: "easy" },
  { id: 219, text: "If you had unlimited resources to start a nonprofit, what would its mission be?", category: "hypothetical", difficulty: "medium" },
  { id: 220, text: "If you could live in any fictional universe, which would you choose?", category: "hypothetical", difficulty: "easy" },
  { id: 221, text: "If you could eliminate one minor inconvenience from daily life forever, what would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 222, text: "If you were given a million dollars but had to spend it in 24 hours, what would you buy?", category: "hypothetical", difficulty: "easy" },
  { id: 223, text: "If you could have been born in a different decade, which would you choose?", category: "hypothetical", difficulty: "medium" },
  { id: 224, text: "If you discovered a new planet, what would you name it?", category: "hypothetical", difficulty: "easy" },
  { id: 225, text: "If you could make one rule that all people had to follow, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 226, text: "If you could know the absolute truth to one question, what would you ask?", category: "hypothetical", difficulty: "hard" },
  { id: 227, text: "If you could trade places with someone for a week, who would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 228, text: "If you could design your dream house, what feature would it definitely have?", category: "hypothetical", difficulty: "easy" },
  { id: 229, text: "If you could bring back one extinct species, which would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 230, text: "If you were the last person on Earth, how would you spend your days?", category: "hypothetical", difficulty: "medium" },
  { id: 231, text: "If you could make one scientific breakthrough happen tomorrow, what would it be?", category: "hypothetical", difficulty: "hard" },
  { id: 232, text: "If you could freeze time for everyone except yourself for one hour, what would you do?", category: "hypothetical", difficulty: "medium" },
  { id: 233, text: "If you could only eat food from one country for the rest of your life, which country would you choose?", category: "hypothetical", difficulty: "easy" },
  { id: 234, text: "If you could add one amendment to your country's constitution, what would it be?", category: "hypothetical", difficulty: "hard" },
  { id: 235, text: "If you could instantly become an expert in one subject, what would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 236, text: "If you could have a conversation with your future self, what would you ask?", category: "hypothetical", difficulty: "medium" },
  { id: 237, text: "If you could create a holiday, what would it celebrate and how?", category: "hypothetical", difficulty: "easy" },
  { id: 238, text: "If you could live to 200 but never retire, would you take the deal?", category: "hypothetical", difficulty: "hard" },
  { id: 239, text: "If you could be a fly on the wall in any room in history, which would you choose?", category: "hypothetical", difficulty: "medium" },
  { id: 240, text: "If you could eliminate one fear permanently, which would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 241, text: "If you could only keep five possessions, what would they be?", category: "hypothetical", difficulty: "medium" },
  { id: 242, text: "If a genie granted you three wishes but none could benefit you directly, what would you wish for?", category: "hypothetical", difficulty: "hard" },
  { id: 243, text: "If you could start a country from scratch, what would be its founding principle?", category: "hypothetical", difficulty: "hard" },
  { id: 244, text: "If you could teleport anywhere right now, where would you go?", category: "hypothetical", difficulty: "easy" },
  { id: 245, text: "If you could choose any person to be your mentor, living or dead, who would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 246, text: "If you could undo one decision in your life, would you do it?", category: "hypothetical", difficulty: "medium" },
  { id: 247, text: "If you could live without sleeping but everyone else still had to, how would you use that time?", category: "hypothetical", difficulty: "medium" },
  { id: 248, text: "If you had to pick one age to remain forever, what age would you choose?", category: "hypothetical", difficulty: "medium" },
  { id: 249, text: "If you could automatically receive a PhD in any field, which would you choose?", category: "hypothetical", difficulty: "easy" },
  { id: 250, text: "If you could experience one thing for the first time again, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 251, text: "If you found out Earth was receiving visitors from another planet in one year, how should we prepare?", category: "hypothetical", difficulty: "hard" },
  { id: 252, text: "If you could change one thing about the way you were raised, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 253, text: "If you could write a best-selling book on any topic, what would it be about?", category: "hypothetical", difficulty: "medium" },
  { id: 254, text: "If you could have any view from your bedroom window, what would it be?", category: "hypothetical", difficulty: "easy" },
  { id: 255, text: "If you could permanently fix one thing about the education system, what would it be?", category: "hypothetical", difficulty: "hard" },
  { id: 256, text: "If you were offered a one-way ticket to Mars, would you go?", category: "hypothetical", difficulty: "hard" },
  { id: 257, text: "If you could speak to all the world's leaders for five minutes, what would you say?", category: "hypothetical", difficulty: "hard" },
  { id: 258, text: "If you could pick any age from history to grow up in, which would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 259, text: "If you could guarantee one thing for your old age, what would it be?", category: "hypothetical", difficulty: "medium" },
  { id: 260, text: "If you could place a permanent webcam anywhere in the world, where would you put it?", category: "hypothetical", difficulty: "easy" },

  // === PERSONAL (65 topics) ===
  { id: 261, text: "Tell us about a time you overcame a significant challenge.", category: "personal", difficulty: "medium" },
  { id: 262, text: "Who has been the most influential person in your life?", category: "personal", difficulty: "easy" },
  { id: 263, text: "What is a childhood memory that you treasure?", category: "personal", difficulty: "easy" },
  { id: 264, text: "What is the bravest thing you have ever done?", category: "personal", difficulty: "medium" },
  { id: 265, text: "What is a mistake that taught you an important lesson?", category: "personal", difficulty: "medium" },
  { id: 266, text: "What are you most proud of in your life?", category: "personal", difficulty: "easy" },
  { id: 267, text: "Tell us about a person who changed your mind about something important.", category: "personal", difficulty: "medium" },
  { id: 268, text: "What is the hardest goodbye you have ever said?", category: "personal", difficulty: "hard" },
  { id: 269, text: "Describe a moment when you felt truly at peace.", category: "personal", difficulty: "medium" },
  { id: 270, text: "What is a risk you took that paid off?", category: "personal", difficulty: "medium" },
  { id: 271, text: "What is a family tradition that means a lot to you?", category: "personal", difficulty: "easy" },
  { id: 272, text: "Tell us about a time when you had to stand up for what you believe in.", category: "personal", difficulty: "hard" },
  { id: 273, text: "What is the kindest thing a stranger has done for you?", category: "personal", difficulty: "easy" },
  { id: 274, text: "What is something you struggled with that made you stronger?", category: "personal", difficulty: "medium" },
  { id: 275, text: "What was the turning point in your career or education?", category: "personal", difficulty: "medium" },
  { id: 276, text: "Tell us about a friendship that has shaped who you are.", category: "personal", difficulty: "medium" },
  { id: 277, text: "What is the scariest experience you have ever had?", category: "personal", difficulty: "medium" },
  { id: 278, text: "What is a goal you set and achieved that surprised even you?", category: "personal", difficulty: "medium" },
  { id: 279, text: "Describe a time you felt completely out of your element.", category: "personal", difficulty: "medium" },
  { id: 280, text: "What is the most meaningful compliment you have received?", category: "personal", difficulty: "easy" },
  { id: 281, text: "Tell us about a teacher or mentor who made a difference in your life.", category: "personal", difficulty: "easy" },
  { id: 282, text: "What is a personal belief you held that you later changed?", category: "personal", difficulty: "hard" },
  { id: 283, text: "What is the happiest moment of your life so far?", category: "personal", difficulty: "easy" },
  { id: 284, text: "Tell us about a time you failed and how you recovered.", category: "personal", difficulty: "medium" },
  { id: 285, text: "What is the best decision you have ever made?", category: "personal", difficulty: "medium" },
  { id: 286, text: "What is a talent or quality you wish you had?", category: "personal", difficulty: "easy" },
  { id: 287, text: "Describe the moment you knew what you wanted to do with your life.", category: "personal", difficulty: "hard" },
  { id: 288, text: "What is a habit you developed that improved your life significantly?", category: "personal", difficulty: "easy" },
  { id: 289, text: "Tell us about a time when you surprised yourself.", category: "personal", difficulty: "medium" },
  { id: 290, text: "What is the most important thing your parents taught you?", category: "personal", difficulty: "easy" },
  { id: 291, text: "What is a dream you have not yet pursued?", category: "personal", difficulty: "medium" },
  { id: 292, text: "Tell us about a moment of unexpected joy.", category: "personal", difficulty: "easy" },
  { id: 293, text: "What was the hardest thing you ever had to forgive?", category: "personal", difficulty: "hard" },
  { id: 294, text: "What is a value you refuse to compromise on?", category: "personal", difficulty: "medium" },
  { id: 295, text: "Tell us about a time when you helped someone and it changed you.", category: "personal", difficulty: "medium" },
  { id: 296, text: "What is the most important relationship in your life and why?", category: "personal", difficulty: "medium" },
  { id: 297, text: "Describe a place that feels like a second home to you.", category: "personal", difficulty: "easy" },
  { id: 298, text: "What is a promise you made to yourself?", category: "personal", difficulty: "medium" },
  { id: 299, text: "Tell us about a time when patience paid off.", category: "personal", difficulty: "medium" },
  { id: 300, text: "What is something about yourself that you have learned to accept?", category: "personal", difficulty: "hard" },
  { id: 301, text: "What was the most difficult conversation you ever had?", category: "personal", difficulty: "hard" },
  { id: 302, text: "What is a moment of serendipity in your life?", category: "personal", difficulty: "medium" },
  { id: 303, text: "Tell us about a loss that gave you perspective.", category: "personal", difficulty: "hard" },
  { id: 304, text: "What is the most courageous thing you have witnessed?", category: "personal", difficulty: "medium" },
  { id: 305, text: "What is a personal accomplishment that no one else knows about?", category: "personal", difficulty: "medium" },
  { id: 306, text: "Tell us about a time when you chose kindness over being right.", category: "personal", difficulty: "medium" },
  { id: 307, text: "What is a childhood dream that you still hold on to?", category: "personal", difficulty: "easy" },
  { id: 308, text: "What is the most vulnerable you have ever allowed yourself to be?", category: "personal", difficulty: "hard" },
  { id: 309, text: "Describe a moment that restored your faith in people.", category: "personal", difficulty: "medium" },
  { id: 310, text: "What is a small act of kindness you witnessed that left a big impression?", category: "personal", difficulty: "easy" },
  { id: 311, text: "Tell us about a time when you had to let go of something you loved.", category: "personal", difficulty: "hard" },
  { id: 312, text: "What is a lesson you learned from a failure that you are grateful for?", category: "personal", difficulty: "medium" },
  { id: 313, text: "What is the best trip you have ever taken and what made it special?", category: "personal", difficulty: "easy" },
  { id: 314, text: "Tell us about someone who believed in you before you believed in yourself.", category: "personal", difficulty: "medium" },
  { id: 315, text: "What is the most meaningful thing you have ever done for someone else?", category: "personal", difficulty: "medium" },
  { id: 316, text: "What was a defining moment of your teenage years?", category: "personal", difficulty: "medium" },
  { id: 317, text: "What is a secret talent or hobby you have?", category: "personal", difficulty: "easy" },
  { id: 318, text: "Describe a time when everything went wrong but it turned out okay.", category: "personal", difficulty: "medium" },
  { id: 319, text: "What is the most important thing you have learned about yourself?", category: "personal", difficulty: "hard" },
  { id: 320, text: "Tell us about a moment when you knew you had grown as a person.", category: "personal", difficulty: "medium" },
  { id: 321, text: "What is a sacrifice you made that was worth it?", category: "personal", difficulty: "hard" },
  { id: 322, text: "What experience made you more empathetic?", category: "personal", difficulty: "medium" },
  { id: 323, text: "Tell us about a tradition you started yourself.", category: "personal", difficulty: "easy" },
  { id: 324, text: "What is a fear you conquered and how did you do it?", category: "personal", difficulty: "medium" },
  { id: 325, text: "What is the greatest adventure you have been on?", category: "personal", difficulty: "easy" },

  // === OPINION (65 topics) ===
  { id: 326, text: "Should social media have age restrictions?", category: "opinion", difficulty: "easy" },
  { id: 327, text: "Is a college degree still worth it?", category: "opinion", difficulty: "medium" },
  { id: 328, text: "Should voting be mandatory?",  category: "opinion", difficulty: "medium" },
  { id: 329, text: "Is remote work better than working in an office?", category: "opinion", difficulty: "easy" },
  { id: 330, text: "Should students be required to learn a second language?", category: "opinion", difficulty: "easy" },
  { id: 331, text: "Is social media doing more harm than good?", category: "opinion", difficulty: "medium" },
  { id: 332, text: "Should tipping culture be abolished?", category: "opinion", difficulty: "medium" },
  { id: 333, text: "Is it better to rent or own a home?", category: "opinion", difficulty: "medium" },
  { id: 334, text: "Should schools teach financial literacy as a core subject?",  category: "opinion", difficulty: "easy" },
  { id: 335, text: "Is it important to follow the news every day?", category: "opinion", difficulty: "easy" },
  { id: 336, text: "Should self-driving cars be allowed on all roads?", category: "opinion", difficulty: "medium" },
  { id: 337, text: "Is it better to specialize in one thing or be a generalist?", category: "opinion", difficulty: "medium" },
  { id: 338, text: "Should pets be allowed in the workplace?", category: "opinion", difficulty: "easy" },
  { id: 339, text: "Is the four-day work week a good idea?", category: "opinion", difficulty: "easy" },
  { id: 340, text: "Should there be limits on how much wealth one person can accumulate?", category: "opinion", difficulty: "hard" },
  { id: 341, text: "Is fast fashion a serious problem?", category: "opinion", difficulty: "medium" },
  { id: 342, text: "Should we explore space or focus on problems here on Earth?", category: "opinion", difficulty: "medium" },
  { id: 343, text: "Is the customer always right?", category: "opinion", difficulty: "easy" },
  { id: 344, text: "Should AI-generated art be considered real art?", category: "opinion", difficulty: "hard" },
  { id: 345, text: "Is it important to buy locally made products?", category: "opinion", difficulty: "easy" },
  { id: 346, text: "Should public transportation be free?", category: "opinion", difficulty: "medium" },
  { id: 347, text: "Is the traditional 9-to-5 work model outdated?", category: "opinion", difficulty: "medium" },
  { id: 348, text: "Should we have a universal basic income?", category: "opinion", difficulty: "hard" },
  { id: 349, text: "Is homework beneficial for students?", category: "opinion", difficulty: "easy" },
  { id: 350, text: "Should zoos still exist?", category: "opinion", difficulty: "medium" },
  { id: 351, text: "Is it better to save money or enjoy it while you are young?", category: "opinion", difficulty: "easy" },
  { id: 352, text: "Should there be a mandatory retirement age?", category: "opinion", difficulty: "medium" },
  { id: 353, text: "Is cancel culture a force for good or harm?", category: "opinion", difficulty: "hard" },
  { id: 354, text: "Should cursive handwriting still be taught in schools?", category: "opinion", difficulty: "easy" },
  { id: 355, text: "Is it better to be a morning person or a night owl?", category: "opinion", difficulty: "easy" },
  { id: 356, text: "Should standardized testing determine college admissions?", category: "opinion", difficulty: "medium" },
  { id: 357, text: "Is print media still relevant in the digital age?", category: "opinion", difficulty: "medium" },
  { id: 358, text: "Should companies be required to disclose their environmental impact?", category: "opinion", difficulty: "medium" },
  { id: 359, text: "Is it ever okay to break a promise?", category: "opinion", difficulty: "medium" },
  { id: 360, text: "Should smartphones be banned in classrooms?", category: "opinion", difficulty: "easy" },
  { id: 361, text: "Is the gig economy good for workers?", category: "opinion", difficulty: "medium" },
  { id: 362, text: "Should we be doing more to preserve endangered languages?", category: "opinion", difficulty: "hard" },
  { id: 363, text: "Is it better to be liked or respected?", category: "opinion", difficulty: "medium" },
  { id: 364, text: "Should parents monitor their children's internet use?", category: "opinion", difficulty: "easy" },
  { id: 365, text: "Is it important to forgive people who have not apologized?", category: "opinion", difficulty: "hard" },
  { id: 366, text: "Should every country have free healthcare?", category: "opinion", difficulty: "hard" },
  { id: 367, text: "Is nostalgia a positive or harmful influence on society?", category: "opinion", difficulty: "medium" },
  { id: 368, text: "Should the legal voting age be lowered?", category: "opinion", difficulty: "medium" },
  { id: 369, text: "Is meritocracy a myth?", category: "opinion", difficulty: "hard" },
  { id: 370, text: "Should tipping be replaced by higher wages?", category: "opinion", difficulty: "medium" },
  { id: 371, text: "Is it ethical to eat meat?", category: "opinion", difficulty: "hard" },
  { id: 372, text: "Should art be government funded?", category: "opinion", difficulty: "medium" },
  { id: 373, text: "Is it better to live in a big city or a small town?", category: "opinion", difficulty: "easy" },
  { id: 374, text: "Should we worry about artificial intelligence?", category: "opinion", difficulty: "medium" },
  { id: 375, text: "Is climate change the greatest challenge of our generation?", category: "opinion", difficulty: "hard" },
  { id: 376, text: "Should children receive an allowance for doing chores?", category: "opinion", difficulty: "easy" },
  { id: 377, text: "Is it acceptable to ghost someone?", category: "opinion", difficulty: "medium" },
  { id: 378, text: "Should professional athletes be role models?", category: "opinion", difficulty: "medium" },
  { id: 379, text: "Is minimalism a realistic lifestyle?", category: "opinion", difficulty: "medium" },
  { id: 380, text: "Should there be an upper age limit for political leaders?", category: "opinion", difficulty: "medium" },
  { id: 381, text: "Is reading fiction a waste of time?", category: "opinion", difficulty: "easy" },
  { id: 382, text: "Should organ donation be opt-out rather than opt-in?", category: "opinion", difficulty: "hard" },
  { id: 383, text: "Is it better to give experiences or material gifts?", category: "opinion", difficulty: "easy" },
  { id: 384, text: "Should history classes focus more on recent events?", category: "opinion", difficulty: "medium" },
  { id: 385, text: "Is having a personal brand important?", category: "opinion", difficulty: "medium" },
  { id: 386, text: "Should people be paid for donating blood?", category: "opinion", difficulty: "medium" },
  { id: 387, text: "Is it possible to be friends with an ex?", category: "opinion", difficulty: "easy" },
  { id: 388, text: "Should libraries evolve beyond books?", category: "opinion", difficulty: "medium" },
  { id: 389, text: "Is hustle culture toxic?", category: "opinion", difficulty: "medium" },
  { id: 390, text: "Should influencers be held to the same standards as journalists?", category: "opinion", difficulty: "hard" },

  // === PROFESSIONAL (65 topics) ===
  { id: 391, text: "What is the most important skill for a leader to have?", category: "professional", difficulty: "medium" },
  { id: 392, text: "How do you handle disagreements with a coworker?", category: "professional", difficulty: "medium" },
  { id: 393, text: "What makes a great team?", category: "professional", difficulty: "medium" },
  { id: 394, text: "What is the best way to give constructive feedback?", category: "professional", difficulty: "medium" },
  { id: 395, text: "How do you manage your time effectively at work?", category: "professional", difficulty: "easy" },
  { id: 396, text: "What is the most valuable lesson you have learned in your career?", category: "professional", difficulty: "medium" },
  { id: 397, text: "How do you stay motivated during repetitive tasks?", category: "professional", difficulty: "easy" },
  { id: 398, text: "What does work-life balance mean to you?", category: "professional", difficulty: "easy" },
  { id: 399, text: "How do you approach learning a new skill for your job?", category: "professional", difficulty: "easy" },
  { id: 400, text: "What is the biggest challenge facing your industry right now?", category: "professional", difficulty: "hard" },
  { id: 401, text: "How do you handle criticism at work?", category: "professional", difficulty: "medium" },
  { id: 402, text: "What is the best career advice you have received?", category: "professional", difficulty: "easy" },
  { id: 403, text: "How important is networking in your field?", category: "professional", difficulty: "medium" },
  { id: 404, text: "What would you change about workplace culture?", category: "professional", difficulty: "medium" },
  { id: 405, text: "How do you deal with a difficult boss or manager?", category: "professional", difficulty: "hard" },
  { id: 406, text: "What is one thing companies should do to retain employees?", category: "professional", difficulty: "medium" },
  { id: 407, text: "How do you prioritize when everything feels urgent?", category: "professional", difficulty: "medium" },
  { id: 408, text: "What is the role of mentorship in professional growth?", category: "professional", difficulty: "medium" },
  { id: 409, text: "How do you prepare for an important presentation?", category: "professional", difficulty: "easy" },
  { id: 410, text: "What is the biggest mistake you have made at work and what did you learn?", category: "professional", difficulty: "hard" },
  { id: 411, text: "How should companies approach diversity and inclusion?", category: "professional", difficulty: "hard" },
  { id: 412, text: "What makes a meeting productive?", category: "professional", difficulty: "easy" },
  { id: 413, text: "How do you stay relevant in a rapidly changing job market?", category: "professional", difficulty: "medium" },
  { id: 414, text: "What is the difference between a manager and a leader?", category: "professional", difficulty: "medium" },
  { id: 415, text: "How do you handle failure in a professional setting?", category: "professional", difficulty: "medium" },
  { id: 416, text: "What is the most underrated professional skill?", category: "professional", difficulty: "medium" },
  { id: 417, text: "How do you build trust within a team?", category: "professional", difficulty: "medium" },
  { id: 418, text: "What role does emotional intelligence play in the workplace?", category: "professional", difficulty: "medium" },
  { id: 419, text: "How do you approach a project you know nothing about?", category: "professional", difficulty: "medium" },
  { id: 420, text: "What is the best way to onboard a new team member?", category: "professional", difficulty: "easy" },
  { id: 421, text: "How do you navigate office politics?", category: "professional", difficulty: "hard" },
  { id: 422, text: "What is one habit that has made you better at your job?", category: "professional", difficulty: "easy" },
  { id: 423, text: "How do you know when it is time to change jobs?", category: "professional", difficulty: "medium" },
  { id: 424, text: "What is the role of creativity in a traditional workplace?", category: "professional", difficulty: "medium" },
  { id: 425, text: "How do you handle imposter syndrome?", category: "professional", difficulty: "hard" },
  { id: 426, text: "What does effective communication look like at work?", category: "professional", difficulty: "easy" },
  { id: 427, text: "How should companies handle remote team building?", category: "professional", difficulty: "medium" },
  { id: 428, text: "What is the most important quality in a colleague?", category: "professional", difficulty: "easy" },
  { id: 429, text: "How do you set boundaries at work without hurting relationships?", category: "professional", difficulty: "hard" },
  { id: 430, text: "What is the future of your profession?", category: "professional", difficulty: "hard" },
  { id: 431, text: "How do you approach negotiating a salary?", category: "professional", difficulty: "medium" },
  { id: 432, text: "What makes a company a great place to work?", category: "professional", difficulty: "easy" },
  { id: 433, text: "How do you handle burnout?", category: "professional", difficulty: "medium" },
  { id: 434, text: "What is the value of cross-functional collaboration?", category: "professional", difficulty: "medium" },
  { id: 435, text: "How do you measure success at work?", category: "professional", difficulty: "medium" },
  { id: 436, text: "What is the hardest part about being a leader?", category: "professional", difficulty: "hard" },
  { id: 437, text: "How should companies support employees' mental health?", category: "professional", difficulty: "medium" },
  { id: 438, text: "What is a professional goal you are currently working toward?", category: "professional", difficulty: "easy" },
  { id: 439, text: "How do you handle a project that is going off the rails?", category: "professional", difficulty: "hard" },
  { id: 440, text: "What is the role of feedback in professional development?", category: "professional", difficulty: "easy" },
  { id: 441, text: "How do you make difficult decisions under pressure?", category: "professional", difficulty: "hard" },
  { id: 442, text: "What is the most important thing to look for in a job?", category: "professional", difficulty: "easy" },
  { id: 443, text: "How do you maintain your professional relationships?", category: "professional", difficulty: "easy" },
  { id: 444, text: "What is the most challenging aspect of working on a team?", category: "professional", difficulty: "medium" },
  { id: 445, text: "How do you keep learning while working full time?", category: "professional", difficulty: "easy" },
  { id: 446, text: "What is the best way to manage conflict in a team?", category: "professional", difficulty: "medium" },
  { id: 447, text: "How do you build your personal brand professionally?", category: "professional", difficulty: "medium" },
  { id: 448, text: "What role does adaptability play in career success?", category: "professional", difficulty: "medium" },
  { id: 449, text: "How do you communicate bad news to your team?", category: "professional", difficulty: "hard" },
  { id: 450, text: "What is the biggest misconception about your profession?", category: "professional", difficulty: "easy" },
  { id: 451, text: "How do you handle competing priorities from different stakeholders?", category: "professional", difficulty: "hard" },
  { id: 452, text: "What is the most rewarding aspect of your job?", category: "professional", difficulty: "easy" },
  { id: 453, text: "How important is continuous improvement in the workplace?", category: "professional", difficulty: "easy" },
  { id: 454, text: "What would you tell someone just starting out in your field?", category: "professional", difficulty: "easy" },
  { id: 455, text: "How do you foster innovation within a team?", category: "professional", difficulty: "hard" },

  // === CREATIVE (65 topics) ===
  { id: 456, text: "Tell a story that begins with: The door was already open when I arrived.", category: "creative", difficulty: "medium" },
  { id: 457, text: "Describe a color to someone who has never seen it.", category: "creative", difficulty: "hard" },
  { id: 458, text: "Invent a new holiday and explain how people would celebrate it.", category: "creative", difficulty: "easy" },
  { id: 459, text: "Describe your life as if it were a movie trailer.", category: "creative", difficulty: "medium" },
  { id: 460, text: "Create a slogan for a product that does not exist yet.", category: "creative", difficulty: "medium" },
  { id: 461, text: "Tell a story using only five words.", category: "creative", difficulty: "hard" },
  { id: 462, text: "Describe your perfect world in one minute.", category: "creative", difficulty: "medium" },
  { id: 463, text: "Make up a new word and define it.", category: "creative", difficulty: "easy" },
  { id: 464, text: "Describe your morning routine from the perspective of your coffee cup.", category: "creative", difficulty: "medium" },
  { id: 465, text: "Pitch a new reality TV show concept.", category: "creative", difficulty: "easy" },
  { id: 466, text: "Write a short toast for a friend's wedding, on the spot.", category: "creative", difficulty: "medium" },
  { id: 467, text: "Describe the soundtrack of your life and what songs are on it.", category: "creative", difficulty: "easy" },
  { id: 468, text: "Tell us a story that starts with the sentence: Nobody expected it to rain frogs.", category: "creative", difficulty: "medium" },
  { id: 469, text: "Design a theme park based on your personality.", category: "creative", difficulty: "medium" },
  { id: 470, text: "Describe what the world would be like if everyone could read minds.", category: "creative", difficulty: "medium" },
  { id: 471, text: "Create a new ice cream flavor and describe it.", category: "creative", difficulty: "easy" },
  { id: 472, text: "Describe your city to an alien who has never been to Earth.", category: "creative", difficulty: "medium" },
  { id: 473, text: "Tell a story about an unlikely friendship between two objects.", category: "creative", difficulty: "medium" },
  { id: 474, text: "Design a new sport and explain the rules.", category: "creative", difficulty: "medium" },
  { id: 475, text: "Write a one-minute speech from the perspective of a historical figure visiting today.", category: "creative", difficulty: "hard" },
  { id: 476, text: "Describe the view from the window of a spaceship.", category: "creative", difficulty: "easy" },
  { id: 477, text: "Create a superhero whose power is completely impractical.", category: "creative", difficulty: "easy" },
  { id: 478, text: "Tell the story of the last book on Earth.", category: "creative", difficulty: "hard" },
  { id: 479, text: "Describe what music looks like if you could see it.", category: "creative", difficulty: "hard" },
  { id: 480, text: "Pitch a new app idea that the world desperately needs.", category: "creative", difficulty: "easy" },
  { id: 481, text: "Create a character who has an unusual job and tell us about their typical day.", category: "creative", difficulty: "medium" },
  { id: 482, text: "Describe your ideal library and what makes it special.", category: "creative", difficulty: "easy" },
  { id: 483, text: "Tell a story that ends with the line: And that is why I never eat spaghetti on Tuesdays.", category: "creative", difficulty: "medium" },
  { id: 484, text: "Design a museum exhibit based on a mundane topic like socks or staplers.", category: "creative", difficulty: "medium" },
  { id: 485, text: "Describe what the Internet would look like if it were a physical place.", category: "creative", difficulty: "medium" },
  { id: 486, text: "Create a new constellation and the myth behind it.", category: "creative", difficulty: "hard" },
  { id: 487, text: "Tell a story about a letter that arrived 50 years too late.", category: "creative", difficulty: "hard" },
  { id: 488, text: "Describe your personality as a type of weather.", category: "creative", difficulty: "easy" },
  { id: 489, text: "Write a one-minute children's story with a moral.", category: "creative", difficulty: "medium" },
  { id: 490, text: "Create a restaurant concept that has never been done before.", category: "creative", difficulty: "medium" },
  { id: 491, text: "Describe the feeling of nostalgia without using the word itself.", category: "creative", difficulty: "hard" },
  { id: 492, text: "Tell a story from the perspective of a tree that has been standing for 500 years.", category: "creative", difficulty: "hard" },
  { id: 493, text: "Design a board game based on everyday life.", category: "creative", difficulty: "medium" },
  { id: 494, text: "Describe what silence sounds like.", category: "creative", difficulty: "hard" },
  { id: 495, text: "Create a travel brochure for an imaginary destination.", category: "creative", difficulty: "easy" },
  { id: 496, text: "Tell a story that takes place entirely in an elevator.", category: "creative", difficulty: "medium" },
  { id: 497, text: "Describe the smell of happiness.", category: "creative", difficulty: "hard" },
  { id: 498, text: "Write a fortune cookie message for the modern age.", category: "creative", difficulty: "easy" },
  { id: 499, text: "Create an origin story for a common everyday object.", category: "creative", difficulty: "medium" },
  { id: 500, text: "Describe what would happen if gravity stopped for ten seconds.", category: "creative", difficulty: "medium" },
  { id: 501, text: "Tell a story that begins and ends with the same sentence.", category: "creative", difficulty: "hard" },
  { id: 502, text: "Pitch a sequel to your favorite movie that takes the story in a completely different direction.", category: "creative", difficulty: "medium" },
  { id: 503, text: "Describe the taste of your favorite memory.", category: "creative", difficulty: "hard" },
  { id: 504, text: "Create a dialogue between the Sun and the Moon.", category: "creative", difficulty: "medium" },
  { id: 505, text: "Describe your dream in the style of a news report.", category: "creative", difficulty: "medium" },
  { id: 506, text: "Write a message to put in a time capsule for people 100 years from now.", category: "creative", difficulty: "medium" },
  { id: 507, text: "Tell the backstory of the person sitting across from you on a bus.", category: "creative", difficulty: "medium" },
  { id: 508, text: "Describe what laughter looks like if it had a physical form.", category: "creative", difficulty: "hard" },
  { id: 509, text: "Create a new genre of music and describe what it sounds like.", category: "creative", difficulty: "hard" },
  { id: 510, text: "Tell a one-minute fairy tale set in the modern world.", category: "creative", difficulty: "medium" },
  { id: 511, text: "Describe your favorite place using only sounds.", category: "creative", difficulty: "hard" },
  { id: 512, text: "Create an advertisement for the most boring product imaginable and make it exciting.", category: "creative", difficulty: "medium" },
  { id: 513, text: "Tell a story where the villain turns out to be the hero.", category: "creative", difficulty: "hard" },
  { id: 514, text: "Describe what friendship would look like as a building.", category: "creative", difficulty: "medium" },
  { id: 515, text: "Write a short acceptance speech for winning an award that does not exist.", category: "creative", difficulty: "easy" },
  { id: 516, text: "Create a recipe using emotions as ingredients.", category: "creative", difficulty: "hard" },
  { id: 517, text: "Describe the last sunset humanity will ever see.", category: "creative", difficulty: "hard" },
  { id: 518, text: "Tell a story about two strangers who find the same lost item.", category: "creative", difficulty: "medium" },
  { id: 519, text: "Describe your week as a weather forecast.", category: "creative", difficulty: "easy" },
  { id: 520, text: "Write the opening paragraph of a novel you will never finish.", category: "creative", difficulty: "medium" }
];
